# 50 pandas puzzle

## Section 1 -- Loading & Exploring the Data

### Question 1: Load csv file into a Dataframe

In [95]:
import pandas as pd
import os

In [96]:
df = pd.read_csv(r"C:\PYTHON\Pandas\ds_with_pandas\all_data.csv")
df.head()

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,176558,USB-C Charging Cable,2,11.95,04/19/19 08:46,"917 1st St, Dallas, TX 75001"
1,NaN,NaN,NaN,NaN,NaN,NaN
2,176559,Bose SoundSport Headphones,1,99.99,04/07/19 22:30,"682 Chestnut St, Boston, MA 02215"
3,176560,Google Phone,1,600,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001"
4,176560,Wired Headphones,1,11.99,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001"

### Question 2: Find the total Rows & Columns

In [97]:
df.shape

(186850, 6)

### Question 3: view the first 5 rows

In [98]:
df.head()

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,176558,USB-C Charging Cable,2,11.95,04/19/19 08:46,"917 1st St, Dallas, TX 75001"
1,NaN,NaN,NaN,NaN,NaN,NaN
2,176559,Bose SoundSport Headphones,1,99.99,04/07/19 22:30,"682 Chestnut St, Boston, MA 02215"
3,176560,Google Phone,1,600,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001"
4,176560,Wired Headphones,1,11.99,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001"

### Question 4: last 5 rows

In [99]:
df.tail()

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
186845,259353,AAA Batteries (4-pack),3,2.99,09/17/19 20:56,"840 Highland St, Los Angeles, CA 90001"
186846,259354,iPhone,1,700,09/01/19 16:00,"216 Dogwood St, San Francisco, CA 94016"
186847,259355,iPhone,1,700,09/23/19 07:39,"220 12th St, San Francisco, CA 94016"
186848,259356,34in Ultrawide Monitor,1,379.99,09/19/19 17:30,"511 Forest St, San Francisco, CA 94016"
186849,259357,USB-C Charging Cable,1,11.95,09/30/19 00:18,"250 Meadow St, San Francisco, CA 94016"

### Question 5: print all column names

In [100]:
df.columns.to_list()

['Order ID',
 'Product',
 'Quantity Ordered',
 'Price Each',
 'Order Date',
 'Purchase Address']

### Question 6: check the data types

In [101]:
df.dtypes

Order ID            str
Product             str
Quantity Ordered    str
Price Each          str
Order Date          str
Purchase Address    str
dtype: object

### Question 7: get a full summary of the DataFrame

In [102]:
df.info

<bound method DataFrame.info of        Order ID                     Product Quantity Ordered Price Each  \
0        176558        USB-C Charging Cable                2      11.95
1           NaN                         NaN              NaN        NaN
2        176559  Bose SoundSport Headphones                1      99.99
3        176560                Google Phone                1        600
4        176560            Wired Headphones                1      11.99
...         ...                         ...              ...        ...
186845   259353      AAA Batteries (4-pack)                3       2.99
186846   259354                      iPhone                1        700
186847   259355                      iPhone                1        700
186848   259356      34in Ultrawide Monitor                1     379.99
186849   259357        USB-C Charging Cable                1      11.95

            Order Date                         Purchase Address
0       04/19/19 08:46             917 1st St, Dallas, TX 75001
1                  NaN                                      NaN
2       04/07/19 22:30        682 Chestnut St, Boston, MA 02215
3       04/12/19 14:38     669 Spruce St, Los Angeles, CA 90001
4       04/12/19 14:38     669 Spruce St, Los Angeles, CA 90001
...                ...                                      ...
186845  09/17/19 20:56   840 Highland St, Los Angeles, CA 90001
186846  09/01/19 16:00  216 Dogwood St, San Francisco, CA 94016
186847  09/23/19 07:39     220 12th St, San Francisco, CA 94016
186848  09/19/19 17:30   511 Forest St, San Francisco, CA 94016
186849  09/30/19 00:18   250 Meadow St, San Francisco, CA 94016

[186850 rows x 6 columns]>

### Question 8: print the list of all unique 'Products'

In [103]:
df['Product'].unique()

<StringArray>
[      'USB-C Charging Cable',                          nan,
 'Bose SoundSport Headphones',               'Google Phone',
           'Wired Headphones',         'Macbook Pro Laptop',
   'Lightning Charging Cable',     '27in 4K Gaming Monitor',
      'AA Batteries (4-pack)',   'Apple Airpods Headphones',
     'AAA Batteries (4-pack)',                     'iPhone',
              'Flatscreen TV',           '27in FHD Monitor',
               '20in Monitor',                   'LG Dryer',
            'ThinkPad Laptop',            'Vareebadd Phone',
         'LG Washing Machine',     '34in Ultrawide Monitor',
                    'Product']
Length: 21, dtype: str

### Question 9: count how many times each product appear

In [104]:
len(df['Product'].unique())

21

### Question 10: print a random sample of 10 rows

In [105]:
df.sample(10)

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
114555,170883,Google Phone,1,600,03/31/19 21:10,"931 Chestnut St, Boston, MA 02215"
108420,165008,Apple Airpods Headphones,1,150,03/23/19 20:04,"89 Cedar St, New York City, NY 10001"
45231,309829,USB-C Charging Cable,1,11.95,12/11/19 14:29,"508 North St, San Francisco, CA 94016"
86838,232060,AAA Batteries (4-pack),2,2.99,07/29/19 15:03,"130 Cedar St, Seattle, WA 98101"
2031,178493,Flatscreen TV,1,300,04/14/19 09:43,"177 Chestnut St, Dallas, TX 75001"
73537,146937,USB-C Charging Cable,1,11.95,01/22/19 19:10,"994 11th St, San Francisco, CA 94016"
135794,208660,AA Batteries (4-pack),1,3.84,05/22/19 04:39,"593 4th St, Atlanta, GA 30301"
137750,279395,Bose SoundSport Headphones,1,99.99,11/22/19 18:50,"707 River St, Los Angeles, CA 90001"
2792,179234,Lightning Charging Cable,1,14.95,04/06/19 14:47,"568 10th St, Portland, OR 97035"
120077,176162,AAA Batteries (4-pack),2,2.99,03/30/19 20:30,"551 Jackson St, New York City, NY 10001"

## Section 2 -- Finding & Handling missing Values

### Question 11: count missing values in ecery column

In [106]:
df.isnull().sum()

Order ID            545
Product             545
Quantity Ordered    545
Price Each          545
Order Date          545
Purchase Address    545
dtype: int64

### Question 12: find the total numbeer of miising values in hole dataset

In [107]:
df.isnull().sum().sum()

np.int64(3270)

### Question 13: drop all rows that have any missing value

In [108]:
df.dropna(inplace=True)

### Question 14: check if there are any duplicate rows

In [109]:
df.duplicated().sum()

np.int64(618)

### Question 15: Remove all duplicate rows from the dataset

In [110]:
df.drop_duplicates(inplace=True)
df.shape

(185687, 6)

### Question 16: check if the Order Date column has any nulls after cleaning

In [111]:
df['Order Date'].isnull().sum()

np.int64(0)

### Question 17: fill missing valused if their exist

In [112]:
df.isnull().sum()

Order ID            0
Product             0
Quantity Ordered    0
Price Each          0
Order Date          0
Purchase Address    0
dtype: int64

## Section 3 -- Column operations

### Question 21: print the quantity order column

In [113]:
# df['Quantity Ordered']
df.head(2)

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,176558,USB-C Charging Cable,2,11.95,04/19/19 08:46,"917 1st St, Dallas, TX 75001"
2,176559,Bose SoundSport Headphones,1,99.99,04/07/19 22:30,"682 Chestnut St, Boston, MA 02215"

### Question 22: convert Quantity order column into integer type

In [114]:
df= df[df['Quantity Ordered'] != 'Quantity Ordered']

In [115]:
df= df.reset_index(drop=True)

In [116]:
df = df[df['Quantity Ordered'].str.isnumeric() == True]
df = df.reset_index(drop=True)

In [117]:
df['Quantity Ordered'] = df['Quantity Ordered'].astype(int)

### Question 23: convert price each column to float type

In [118]:
pd.to_numeric(df['Price Each'])
df = df[df['Order ID'].str.isnumeric() == True]
df = df.reset_index(drop=True)

In [119]:
df['Price Each'] = df['Price Each'].astype(float)

### Question 24: add a new column called revenue

In [120]:
df['Revenue'] = df['Quantity Ordered'] * df['Price Each']
df.head()

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,Revenue
0,176558,USB-C Charging Cable,2,11.95,04/19/19 08:46,"917 1st St, Dallas, TX 75001",23.90
1,176559,Bose SoundSport Headphones,1,99.99,04/07/19 22:30,"682 Chestnut St, Boston, MA 02215",99.99
2,176560,Google Phone,1,600.00,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001",600.00
3,176560,Wired Headphones,1,11.99,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001",11.99
4,176561,Wired Headphones,1,11.99,04/30/19 09:27,"333 8th St, Los Angeles, CA 90001",11.99

### Question 25: find the maximum price in the price each column

In [121]:
df['Price Each'].max()

np.float64(1700.0)

### Question 26: find the minimum price in the price each column

In [122]:
df['Price Each'].min()

np.float64(2.99)

### Question 27: find the average price across all orders

In [123]:
round(df['Price Each'].mean(),2)

np.float64(184.52)

### Question 28: get full statistics of the price Each column

In [124]:
df['Price Each'].describe()

count    185686.000000
mean        184.519255
std         332.843838
min           2.990000
25%          11.950000
50%          14.950000
75%         150.000000
max        1700.000000
Name: Price Each, dtype: float64

### Question 29: find the toatl revenue across all orders

In [125]:
# df['Revenue'].sum()
# (34465537.94)
round(df['Price Each'].sum(),2)

np.float64(34262642.47)

### Question 30: find the average order quantity

In [126]:
df['Quantity Ordered'].mean()

np.float64(1.1245435843305365)

## Section 4 -- Filtering & Sorting rows

### Question 31: filter all orders where quantity ordered is greater than 1

In [127]:
bulk_orders = df[df['Quantity Ordered'] > 1]
print(bulk_orders.shape)

(17395, 7)

### Question 32: find all orders for a specific product -- Usb-c charging cable

In [128]:
usbc_orders = df[df['Product'] =='USB-C Charging Cable']
print(usbc_orders.shape)

(21859, 7)

### question 33: filter all orders where price each is more than 100

In [129]:
expensive = df[df['Price Each'] > 100]
print(expensive.shape)

(68900, 7)

### question 34: sort the dataframe by price each from highest to lowest

In [130]:
df_sorted = df.sort_values('Price Each', ascending=False)
print(df_sorted.head())

       Order ID             Product  Quantity Ordered  Price Each  \
185634   259308  Macbook Pro Laptop                 1      1700.0
8        176565  Macbook Pro Laptop                 1      1700.0
185624   259299  Macbook Pro Laptop                 1      1700.0
30916    296346  Macbook Pro Laptop                 1      1700.0
30895    296325  Macbook Pro Laptop                 1      1700.0

            Order Date                        Purchase Address  Revenue
185634  09/26/19 19:16            912 8th St, Boston, MA 02215   1700.0
8       04/24/19 10:38  915 Willow St, San Francisco, CA 94016   1700.0
185624  09/30/19 23:59  240 Chestnut St, Los Angeles, CA 90001   1700.0
30916   12/25/19 07:39         818 Willow St, Boston, MA 02215   1700.0
30895   12/28/19 22:52         755 Adams St, Seattle, WA 98101   1700.0

### question 35: sort the dataframe by quantity order from lowest to highest

In [131]:
df.sort_values('Quantity Ordered',ascending=True).head()

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,Revenue
185684,259356,34in Ultrawide Monitor,1,379.99,09/19/19 17:30,"511 Forest St, San Francisco, CA 94016",379.99
176044,250048,Flatscreen TV,1,300.00,09/29/19 07:03,"11 Lake St, Seattle, WA 98101",300.00
176045,250049,20in Monitor,1,109.99,09/11/19 09:22,"320 8th St, Dallas, TX 75001",109.99
176047,250051,Bose SoundSport Headphones,1,99.99,09/15/19 15:30,"828 Ridge St, Portland, OR 97035",99.99
185668,259341,27in 4K Gaming Monitor,1,389.99,09/24/19 22:16,"501 Adams St, Seattle, WA 98101",389.99

### question 36: Filter orders that have Revenue greater than 500

In [132]:
max_revenue = df[df['Revenue']> 500]
print(max_revenue)

       Order ID             Product  Quantity Ordered  Price Each  \
2        176560        Google Phone                 1      600.00
8        176565  Macbook Pro Laptop                 1     1700.00
10       176567        Google Phone                 1      600.00
17       176574        Google Phone                 1      600.00
25       176581              iPhone                 1      700.00
...         ...                 ...               ...         ...
185651   259324  Macbook Pro Laptop                 1     1700.00
185672   259345     ThinkPad Laptop                 1      999.99
185677   259350        Google Phone                 1      600.00
185682   259354              iPhone                 1      700.00
185683   259355              iPhone                 1      700.00

            Order Date                         Purchase Address  Revenue
2       04/12/19 14:38     669 Spruce St, Los Angeles, CA 90001   600.00
8       04/24/19 10:38   915 Willow St, San Francisco, CA 94016  1700.00
10      04/18/19 17:18        444 7th St, Los Angeles, CA 90001   600.00
17      04/03/19 19:42        20 Hill St, Los Angeles, CA 90001   600.00
25      04/09/19 21:38          84 Jackson St, Boston, MA 02215   700.00
...                ...                                      ...      ...
185651  09/29/19 13:37    926 North St, San Francisco, CA 94016  1700.00
185672  09/21/19 23:12  406 Dogwood St, San Francisco, CA 94016   999.99
185677  09/30/19 13:49    519 Maple St, San Francisco, CA 94016   600.00
185682  09/01/19 16:00  216 Dogwood St, San Francisco, CA 94016   700.00
185683  09/23/19 07:39     220 12th St, San Francisco, CA 94016   700.00

[22575 rows x 7 columns]

### question 37: select any product and price each column

In [133]:
df[['Product','Price Each']].head()

                      Product  Price Each
0        USB-C Charging Cable       11.95
1  Bose SoundSport Headphones       99.99
2                Google Phone      600.00
3            Wired Headphones       11.99
4            Wired Headphones       11.99

### question 38: find all order placed in los angeles

In [134]:
df['City'] = df['Purchase Address'].apply(lambda x:" ".join(x.split(",")[1]))

In [135]:
df.head()

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,Revenue,City
0,176558,USB-C Charging Cable,2,11.95,04/19/19 08:46,"917 1st St, Dallas, TX 75001",23.90,D a l l a s
1,176559,Bose SoundSport Headphones,1,99.99,04/07/19 22:30,"682 Chestnut St, Boston, MA 02215",99.99,B o s t o n
2,176560,Google Phone,1,600.00,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001",600.00,L o s A n g e l e s
3,176560,Wired Headphones,1,11.99,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001",11.99,L o s A n g e l e s
4,176561,Wired Headphones,1,11.99,04/30/19 09:27,"333 8th St, Los Angeles, CA 90001",11.99,L o s A n g e l e s

In [136]:
la__orders = df[df['Purchase Address'].str.contains('Los Angeles')]

In [137]:
print(la__orders.head())

   Order ID           Product  Quantity Ordered  Price Each      Order Date  \
2    176560      Google Phone                 1      600.00  04/12/19 14:38
3    176560  Wired Headphones                 1       11.99  04/12/19 14:38
4    176561  Wired Headphones                 1       11.99  04/30/19 09:27
10   176567      Google Phone                 1      600.00  04/18/19 17:18
17   176574      Google Phone                 1      600.00  04/03/19 19:42

                        Purchase Address  Revenue                     City
2   669 Spruce St, Los Angeles, CA 90001   600.00    L o s   A n g e l e s
3   669 Spruce St, Los Angeles, CA 90001    11.99    L o s   A n g e l e s
4      333 8th St, Los Angeles, CA 90001    11.99    L o s   A n g e l e s
10     444 7th St, Los Angeles, CA 90001   600.00    L o s   A n g e l e s
17     20 Hill St, Los Angeles, CA 90001   600.00    L o s   A n g e l e s

### question 39: filter orders where both Quantity > 1 AND price > 50

In [140]:
df[(df['Quantity Ordered']> 1) & (df['Price Each']> 50)].head()

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,Revenue,City
158,176710,20in Monitor,2,109.99,04/07/19 10:00,"848 West St, Dallas, TX 75001",219.98,D a l l a s
264,176809,Bose SoundSport Headphones,2,99.99,04/19/19 01:14,"278 13th St, San Francisco, CA 94016",199.98,S a n F r a n c i s c o
603,177139,Apple Airpods Headphones,2,150.00,04/03/19 14:05,"723 Madison St, San Francisco, CA 94016",300.00,S a n F r a n c i s c o
1261,177765,Bose SoundSport Headphones,2,99.99,04/16/19 13:57,"528 1st St, New York City, NY 10001",199.98,N e w Y o r k C i t y
1369,177866,Apple Airpods Headphones,2,150.00,04/06/19 17:11,"855 Main St, Los Angeles, CA 90001",300.00,L o s A n g e l e s

### question 40: reset the index of the DataFrame after filtering

In [141]:
df.reset_index(drop=True)

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,Revenue,City
0,176558,USB-C Charging Cable,2,11.95,04/19/19 08:46,"917 1st St, Dallas, TX 75001",23.90,D a l l a s
1,176559,Bose SoundSport Headphones,1,99.99,04/07/19 22:30,"682 Chestnut St, Boston, MA 02215",99.99,B o s t o n
2,176560,Google Phone,1,600.00,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001",600.00,L o s A n g e l e s
3,176560,Wired Headphones,1,11.99,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001",11.99,L o s A n g e l e s
4,176561,Wired Headphones,1,11.99,04/30/19 09:27,"333 8th St, Los Angeles, CA 90001",11.99,L o s A n g e l e s
...,...,...,...,...,...,...,...,...
185681,259353,AAA Batteries (4-pack),3,2.99,09/17/19 20:56,"840 Highland St, Los Angeles, CA 90001",8.97,L o s A n g e l e s
185682,259354,iPhone,1,700.00,09/01/19 16:00,"216 Dogwood St, San Francisco, CA 94016",700.00,S a n F r a n c i s c o
185683,259355,iPhone,1,700.00,09/23/19 07:39,"220 12th St, San Francisco, CA 94016",700.00,S a n F r a n c i s c o
185684,259356,34in Ultrawide Monitor,1,379.99,09/19/19 17:30,"511 Forest St, San Francisco, CA 94016",379.99,S a n F r a n c i s c o
185685,259357,USB-C Charging Cable,1,11.95,09/30/19 00:18,"250 Meadow St, San Francisco, CA 94016",11.95,S a n F r a n c i s c o