# 50 pandas puzzle

## Section 1 -- Loading & Exploring the Data

### Question 1: Load csv file into a Dataframe

In [269]:
import pandas as pd
import os

In [270]:
df = pd.read_csv(r"C:\PYTHON\Pandas\ds_with_pandas\all_data.csv")
df.head()

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,176558,USB-C Charging Cable,2,11.95,04/19/19 08:46,"917 1st St, Dallas, TX 75001"
1,NaN,NaN,NaN,NaN,NaN,NaN
2,176559,Bose SoundSport Headphones,1,99.99,04/07/19 22:30,"682 Chestnut St, Boston, MA 02215"
3,176560,Google Phone,1,600,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001"
4,176560,Wired Headphones,1,11.99,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001"

### Question 2: Find the total Rows & Columns

In [271]:
df.shape

(186850, 6)

### Question 3: view the first 5 rows

In [272]:
df.head()

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,176558,USB-C Charging Cable,2,11.95,04/19/19 08:46,"917 1st St, Dallas, TX 75001"
1,NaN,NaN,NaN,NaN,NaN,NaN
2,176559,Bose SoundSport Headphones,1,99.99,04/07/19 22:30,"682 Chestnut St, Boston, MA 02215"
3,176560,Google Phone,1,600,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001"
4,176560,Wired Headphones,1,11.99,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001"

### Question 4: last 5 rows

In [273]:
df.tail()

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
186845,259353,AAA Batteries (4-pack),3,2.99,09/17/19 20:56,"840 Highland St, Los Angeles, CA 90001"
186846,259354,iPhone,1,700,09/01/19 16:00,"216 Dogwood St, San Francisco, CA 94016"
186847,259355,iPhone,1,700,09/23/19 07:39,"220 12th St, San Francisco, CA 94016"
186848,259356,34in Ultrawide Monitor,1,379.99,09/19/19 17:30,"511 Forest St, San Francisco, CA 94016"
186849,259357,USB-C Charging Cable,1,11.95,09/30/19 00:18,"250 Meadow St, San Francisco, CA 94016"

### Question 5: print all column names

In [274]:
df.columns.to_list()

['Order ID',
 'Product',
 'Quantity Ordered',
 'Price Each',
 'Order Date',
 'Purchase Address']

### Question 6: check the data types

In [275]:
df.dtypes

Order ID            str
Product             str
Quantity Ordered    str
Price Each          str
Order Date          str
Purchase Address    str
dtype: object

### Question 7: get a full summary of the DataFrame

In [276]:
df.info

<bound method DataFrame.info of        Order ID                     Product Quantity Ordered Price Each  \
0        176558        USB-C Charging Cable                2      11.95
1           NaN                         NaN              NaN        NaN
2        176559  Bose SoundSport Headphones                1      99.99
3        176560                Google Phone                1        600
4        176560            Wired Headphones                1      11.99
...         ...                         ...              ...        ...
186845   259353      AAA Batteries (4-pack)                3       2.99
186846   259354                      iPhone                1        700
186847   259355                      iPhone                1        700
186848   259356      34in Ultrawide Monitor                1     379.99
186849   259357        USB-C Charging Cable                1      11.95

            Order Date                         Purchase Address
0       04/19/19 08:46             917 1st St, Dallas, TX 75001
1                  NaN                                      NaN
2       04/07/19 22:30        682 Chestnut St, Boston, MA 02215
3       04/12/19 14:38     669 Spruce St, Los Angeles, CA 90001
4       04/12/19 14:38     669 Spruce St, Los Angeles, CA 90001
...                ...                                      ...
186845  09/17/19 20:56   840 Highland St, Los Angeles, CA 90001
186846  09/01/19 16:00  216 Dogwood St, San Francisco, CA 94016
186847  09/23/19 07:39     220 12th St, San Francisco, CA 94016
186848  09/19/19 17:30   511 Forest St, San Francisco, CA 94016
186849  09/30/19 00:18   250 Meadow St, San Francisco, CA 94016

[186850 rows x 6 columns]>

### Question 8: print the list of all unique 'Products'

In [277]:
df['Product'].unique()

<StringArray>
[      'USB-C Charging Cable',                          nan,
 'Bose SoundSport Headphones',               'Google Phone',
           'Wired Headphones',         'Macbook Pro Laptop',
   'Lightning Charging Cable',     '27in 4K Gaming Monitor',
      'AA Batteries (4-pack)',   'Apple Airpods Headphones',
     'AAA Batteries (4-pack)',                     'iPhone',
              'Flatscreen TV',           '27in FHD Monitor',
               '20in Monitor',                   'LG Dryer',
            'ThinkPad Laptop',            'Vareebadd Phone',
         'LG Washing Machine',     '34in Ultrawide Monitor',
                    'Product']
Length: 21, dtype: str

### Question 9: count how many times each product appear

In [278]:
len(df['Product'].unique())

21

### Question 10: print a random sample of 10 rows

In [279]:
df.sample(10)

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
156734,261213,AAA Batteries (4-pack),2,2.99,10/08/19 11:53,"560 12th St, Boston, MA 02215"
26964,244877,AAA Batteries (4-pack),1,2.99,08/16/19 19:05,"435 9th St, Boston, MA 02215"
175825,248790,USB-C Charging Cable,1,11.95,09/07/19 14:36,"358 Spruce St, San Francisco, CA 94016"
136349,209195,AA Batteries (4-pack),1,3.84,05/21/19 12:51,"222 Lakeview St, Portland, OR 97035"
145522,286830,Apple Airpods Headphones,1,150,11/11/19 17:57,"533 2nd St, Los Angeles, CA 90001"
3895,180294,AA Batteries (4-pack),1,3.84,04/20/19 18:33,"132 Main St, Boston, MA 02215"
114844,171159,AAA Batteries (4-pack),1,2.99,03/19/19 10:27,"899 7th St, New York City, NY 10001"
164592,268709,AAA Batteries (4-pack),1,2.99,10/09/19 16:22,"996 Sunset St, Boston, MA 02215"
100596,218463,Apple Airpods Headphones,1,150,06/21/19 22:06,"279 Willow St, Los Angeles, CA 90001"
90682,235753,Lightning Charging Cable,1,14.95,07/04/19 15:12,"761 Lake St, Portland, OR 97035"

## Section 2 -- Finding & Handling missing Values

### Question 11: count missing values in ecery column

In [280]:
df.isnull().sum()

Order ID            545
Product             545
Quantity Ordered    545
Price Each          545
Order Date          545
Purchase Address    545
dtype: int64

### Question 12: find the total numbeer of miising values in hole dataset

In [281]:
df.isnull().sum().sum()

np.int64(3270)

### Question 13: drop all rows that have any missing value

In [282]:
df.dropna(inplace=True)

### Question 14: check if there are any duplicate rows

In [283]:
df.duplicated().sum()

np.int64(618)

### Question 15: Remove all duplicate rows from the dataset

In [284]:
df.drop_duplicates(inplace=True)
df.shape

(185687, 6)

### Question 16: check if the Order Date column has any nulls after cleaning

In [285]:
df['Order Date'].isnull().sum()

np.int64(0)

### Question 17: fill missing valused if their exist

In [286]:
df.isnull().sum()

Order ID            0
Product             0
Quantity Ordered    0
Price Each          0
Order Date          0
Purchase Address    0
dtype: int64

## Section 3 -- Column operations

### Question 21: print the quantity order column

In [287]:
# df['Quantity Ordered']
df.head(2)

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,176558,USB-C Charging Cable,2,11.95,04/19/19 08:46,"917 1st St, Dallas, TX 75001"
2,176559,Bose SoundSport Headphones,1,99.99,04/07/19 22:30,"682 Chestnut St, Boston, MA 02215"

### Question 22: convert Quantity order column into integer type

In [288]:
df= df[df['Quantity Ordered'] != 'Quantity Ordered']

In [289]:
df= df.reset_index(drop=True)

In [296]:
df = df[df['Quantity Ordered'].str.isnumeric() == True]
df = df.reset_index(drop=True)

In [299]:
df['Quantity Ordered'] = df['Quantity Ordered'].astype(int)

### Question 23: convert price each column to float type

In [295]:
pd.to_numeric(df['Price Each'])
df = df[df['Order ID'].str.isnumeric() == True]
df = df.reset_index(drop=True)

In [300]:
df['Price Each'] = df['Price Each'].astype(float)

### Question 24: add a new column called revenue

In [302]:
df['Revenue'] = df['Quantity Ordered'] * df['Price Each']
df.head()

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,Revenue
0,176558,USB-C Charging Cable,2,11.95,04/19/19 08:46,"917 1st St, Dallas, TX 75001",23.90
1,176559,Bose SoundSport Headphones,1,99.99,04/07/19 22:30,"682 Chestnut St, Boston, MA 02215",99.99
2,176560,Google Phone,1,600.00,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001",600.00
3,176560,Wired Headphones,1,11.99,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001",11.99
4,176561,Wired Headphones,1,11.99,04/30/19 09:27,"333 8th St, Los Angeles, CA 90001",11.99

### Question 25: find the maximum price in the price each column

In [303]:
df['Price Each'].max()

np.float64(1700.0)

### Question 26: find the minimum price in the price each column

In [304]:
df['Price Each'].min()

np.float64(2.99)

### Question 27: find the average price across all orders

In [306]:
round(df['Price Each'].mean(),2)

np.float64(184.52)

### Question 28: get full statistics of the price Each column

In [307]:
df['Price Each'].describe()

count    185686.000000
mean        184.519255
std         332.843838
min           2.990000
25%          11.950000
50%          14.950000
75%         150.000000
max        1700.000000
Name: Price Each, dtype: float64

### Question 29: find the toatl revenue across all orders

In [310]:
# df['Revenue'].sum()
# (34465537.94)
round(df['Price Each'].sum(),2)

np.float64(34262642.47)

### Question 30: find the average order quantity

In [311]:
df['Quantity Ordered'].mean()

np.float64(1.1245435843305365)

## Section 4 -- Filtering & Sorting rows

### Question 31: filter all orders where quantity ordered is greater than 1

In [314]:
bulk_orders = df[df['Quantity Ordered'] > 1]
print(bulk_orders.shape)

(17395, 7)

### Question 32: filter all orders for a specific product -- Usb-c charging cable

In [315]:
usbc_orders = df[df['Product'] =='USB-C Charging Cable']
print(usbc_orders.shape)

(21859, 7)