# Medical data analysis

In [ ]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns 
import plotly.express as px

In [8]:
df= pd.read_csv(r"C:\Users\PRATHAMESH\Desktop\Data Science\medical-charges.csv")

In [9]:
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   region    1338 non-null   object
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB

In [11]:
df.describe()

               age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

In [13]:
df.shape

(1338, 7)

In [15]:
df.columns.to_list()

['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'charges']

In [18]:
df.dtypes

age           int64
sex          object
bmi         float64
children      int64
smoker       object
region       object
charges     float64
dtype: object

In [20]:
df.describe(include='all')

,age,sex,bmi,children,smoker,region,charges
count,1338.000000,1338,1338.000000,1338.000000,1338,1338,1338.000000
unique,NaN,2,NaN,NaN,2,4,NaN
top,NaN,male,NaN,NaN,no,southeast,NaN
freq,NaN,676,NaN,NaN,1064,364,NaN
mean,39.207025,NaN,30.663397,1.094918,NaN,NaN,13270.422265
std,14.049960,NaN,6.098187,1.205493,NaN,NaN,12110.011237
min,18.000000,NaN,15.960000,0.000000,NaN,NaN,1121.873900
25%,27.000000,NaN,26.296250,0.000000,NaN,NaN,4740.287150
50%,39.000000,NaN,30.400000,1.000000,NaN,NaN,9382.033000
75%,51.000000,NaN,34.693750,2.000000,NaN,NaN,16639.912515
max,64.000000,NaN,53.130000,5.000000,NaN,NaN,63770.428010

In [21]:
df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [23]:
df.sample(5)

      age     sex     bmi  children smoker     region      charges
1269   45    male  27.500         3     no  southwest   8615.30000
175    63  female  37.700         0    yes  southwest  48824.45000
201    48  female  32.230         1     no  southeast   8871.15170
442    18    male  43.010         0     no  southeast   1149.39590
601    51    male  31.635         0     no  northwest   9174.13565

In [25]:
df.duplicated().sum()

np.int64(1)

In [26]:
df.duplicated(keep=False)

0       False
1       False
2       False
3       False
4       False
        ...
1333    False
1334    False
1335    False
1336    False
1337    False
Length: 1338, dtype: bool

In [35]:
nums_cols = df.select_dtypes(include='number').columns.tolist()
cat_cols = df.select_dtypes(include='object').columns.tolist()
print(f'number column : {nums_cols} \ncategorical columns : {cat_cols}')

number column : ['age', 'bmi', 'children', 'charges']
categorical columns : ['sex', 'smoker', 'region']

In [37]:
df.memory_usage(deep=True).sort_values(ascending = False)

region      77604
sex         72238
smoker      68512
age         10704
bmi         10704
children    10704
charges     10704
Index         132
dtype: int64

In [39]:
df.corr(numeric_only = True)

               age       bmi  children   charges
age       1.000000  0.109272  0.042469  0.299008
bmi       0.109272  1.000000  0.012759  0.198341
children  0.042469  0.012759  1.000000  0.067998
charges   0.299008  0.198341  0.067998  1.000000

In [40]:
df[df['children'] > 4 ]

      age     sex     bmi  children smoker     region      charges
32     19  female  28.600         5     no  southwest   4687.79700
71     31    male  28.500         5     no  northeast   6799.45800
166    20  female  37.000         5     no  southwest   4830.63000
413    25    male  23.900         5     no  southwest   5080.09600
425    45    male  24.310         5     no  southeast   9788.86590
438    52  female  46.750         5     no  southeast  12592.53450
568    49  female  31.900         5     no  southwest  11552.90400
640    33    male  42.400         5     no  southwest   6666.24300
877    33    male  33.440         5     no  southeast   6653.78860
932    46    male  25.800         5     no  southwest  10096.97000
937    39  female  24.225         5     no  northwest   8965.79575
969    39  female  34.320         5     no  southeast   8596.82780
984    20    male  30.115         5     no  northeast   4915.05985
1085   39  female  18.300         5    yes  southwest  19023.26000
1116   41    male  29.640         5     no  northeast   9222.40260
1130   39  female  23.870         5     no  southeast   8582.30230
1245   28    male  24.300         5     no  southwest   5615.36900
1272   43    male  25.520         5     no  southeast  14478.33015

In [44]:
df[(df['children']> 4) & (df['age'] > 30)]

      age     sex     bmi  children smoker     region      charges
71     31    male  28.500         5     no  northeast   6799.45800
425    45    male  24.310         5     no  southeast   9788.86590
438    52  female  46.750         5     no  southeast  12592.53450
568    49  female  31.900         5     no  southwest  11552.90400
640    33    male  42.400         5     no  southwest   6666.24300
877    33    male  33.440         5     no  southeast   6653.78860
932    46    male  25.800         5     no  southwest  10096.97000
937    39  female  24.225         5     no  northwest   8965.79575
969    39  female  34.320         5     no  southeast   8596.82780
1085   39  female  18.300         5    yes  southwest  19023.26000
1116   41    male  29.640         5     no  northeast   9222.40260
1130   39  female  23.870         5     no  southeast   8582.30230
1272   43    male  25.520         5     no  southeast  14478.33015

In [45]:
df[(df['children'] > 4) | (df['age'] > 40)]

      age     sex    bmi  children smoker     region      charges
6      46  female  33.44         1     no  southeast   8240.58960
9      60  female  25.84         0     no  northwest  28923.13692
11     62  female  26.29         0    yes  southeast  27808.72510
13     56  female  39.82         0     no  southeast  11090.71780
16     52  female  30.78         1     no  northeast  10797.33620
...   ...     ...    ...       ...    ...        ...          ...
1329   52    male  38.60         2     no  southwest  10325.20600
1330   57  female  25.74         2     no  southeast  12629.16560
1332   52  female  44.70         3     no  southwest  11411.68500
1333   50    male  30.97         3     no  northwest  10600.54830
1337   61  female  29.07         0    yes  northwest  29141.36030

[649 rows x 7 columns]

In [47]:
df[~df['children'] == 'inactive']

Empty DataFrame
Columns: [age, sex, bmi, children, smoker, region, charges]
Index: []

In [53]:
reg = ['yes','no']
df[df['smoker'].isin(reg)]

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]